### ISSUE TITLE
请问这个谷歌播放的视频这个需要钱来购买吗？

### ISSUE THREAD

**Issue by xyy7260** [aitexiaoy/rtsp_chrome_demo#2]

**Comment by aitexiaoy** [comment]
不需要，免费的。

**Comment by aitexiaoy** [comment]
在IE下可以采用VLC，在chrome下可以利用附件中的插件播放。

**Comment by xyy7260** [comment]
好的老大， 我可以把ie的VLC代码 和chrome插件 同时写在代码中不会出现问题吧，  毕竟VLC只能在ie上显示，在页面也就会占据元素位置到时我处理一 在ie 显示val 在谷歌显示插件， 还有一个问题就是 怎么兼容其他浏览器呢

**Comment by aitexiaoy** [comment]
同学，你好！
    Demo只是提供了一种播放rtsp视频的可能性。如果要同时支持IE与chrome，我建议可以将不同浏览器的播放窗口单独做成一个html页面。然后在父页面中判断浏览器类型，然后通过iframe的方式加载播放窗口。
    对于其他浏览器，暂时没有找到相关的插件。如果你找到了也可以通知我。非常感谢！


在2019年03月13日 18:05，hy<notifications@github.com> 写道：

好的老大， 我可以把ie的VLC代码 和chrome插件 同时写在代码中不会出现问题吧， 毕竟VLC只能在ie上显示，在页面也就会占据元素位置到时我处理一 在ie 显示val 在谷歌显示插件， 还有一个问题就是 怎么兼容其他浏览器呢

**Comment by xyy7260** [comment]
@aitexiaoy  好谢谢给的意见

**Comment by xyy7260** [comment]
在demo中我打开出现这样情况
vxgplayer isFrame: false
vxgplayer-1.8.40.min.js:1 vxgplayer browserSupportsPluginPnacl: true
Access to resource at 'file:///Users/xiaohuhh/Downloads/Chrome.RTSP.Player-master/src/pnacl/Release/media_player.nmf' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
NativeClient: access to manifest url was denied.
Not installed vxg_media_player

请问是什么意思呢

**Comment by xyy7260** [comment]
@aitexiaoy  在请问一下， 你有没有在 react 和Vue使用呢？ 是怎么处理播放过程呢，因为我这边使用在react上出现 NativeClient: manifest JSON parsing failed: Line: 1, column: 1, Unexpected token.
所以想看看您的代码

**Comment by xyy7260** [comment]
@aitexiaoy  我很需要使用和这个插件。 我想把我的实现步骤告诉你看看，
我的步骤是我把这个js引入到我的html中复制html播放那些代码，但是我没有启动你项目的index.js我怀疑是不是应为这个东西造成无法播放的呢？ 谢谢希望能指点一下

**Comment by aitexiaoy** [comment]
你好，很抱歉不能给你更多的帮助。我只是实现了这个简单的demo代码。更深入的使用建议去插件的官网查看相关文档。你也可以发送你的代码到我的邮箱aitexiaoy@163.com共同探讨一下。

**Comment by aitexiaoy** [comment]
插件的API请参考：https://www.videoexpertsgroup.com/nacl_player_api/
