### ISSUE TITLE
你好，你遇到过这样的问题吗TypeError: t.module.command is not a function

### ISSUE THREAD

**Issue by xyy7260** [aitexiaoy/rtsp_chrome_demo#3]
环境：
react
react-router
遇到的问题就是：
TypeError: t.module.command is not a function
t.stop
http://localhost:8099/vxgplayer-1.8.40.min.js:1:17231
因为我在当前的页面播放rtsp视频，跳转去了别的页面，有返回到刚刚播放rtsp视频的页面造成
vxgplayer-1.8.40.min.js一些内容未定义的 undefined了 请问你遇到过这样的问题吗

**Comment by aitexiaoy** [comment]
抱歉，没遇到。

**Comment by sendtion** [comment]
我也遇到了，大佬解决了吗
